import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { checkViewport } from "./helpers/browser-viewport.mjs";
import { build } from "vite";
import reactPlugin from "@vitejs/plugin-react";
const root = path.resolve(import.meta.dirname, "..");
const browser = process.env.TEXT_EFFECT_TEST_BROWSER || ["C:/Program Files/Google/Chrome/Application/chrome.exe", "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"].find(existsSync);
assert.ok(browser, "A local Chromium browser is required");
const temp = mkdtempSync(path.join(tmpdir(), "zichang-ui-"));
const entry = path.join(temp, "entry.mjs");
writeFileSync(entry, `import React from "react"; import {createRoot} from "react-dom/client"; import {flushSync} from "react-dom"; import Home from ${JSON.stringify(path.join(root, "app/page.tsx").replaceAll("\\", "/"))};
import {Conversation} from "@/components/ui/conversation/Conversation";
const check=(ok,message)=>{if(!ok)throw Error(message)};
flushSync(()=>createRoot(document.querySelector('#app')).render(React.createElement(Home)));
const click=element=>flushSync(()=>element.click());
const tab=name=>click([...document.querySelectorAll('[aria-label="组件分类"] button')].find(e=>e.textContent.startsWith(name)));
const edit=(element,value)=>flushSync(()=>{Object.getOwnPropertyDescriptor(element instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}));});
const detailGeometry=label=>{const drawer=document.querySelector('.detail-drawer');check(drawer.scrollWidth<=drawer.clientWidth+1,label+': detail overflow');const stage=document.querySelector('.workbench-stage');const editor=document.querySelector('.workbench-editor');if(stage&&editor){const a=stage.getBoundingClientRect(),b=editor.getBoundingClientRect();check(b.left>=a.right-1||b.top>=a.bottom-1,label+': preview and controls overlap');}};
(async()=>{try {
tab('按钮');check(document.querySelectorAll('.effect-card').length===18,'Button category did not filter');check(!document.querySelector('.playground-bar'),'Text controls leaked into buttons');
const button=document.querySelector('.zc-button');click(button);check(document.querySelector('.ui-preview-content small').textContent.includes('1'),'Button interaction failed');
click(document.querySelector('.ui-configure'));check(document.querySelector('.detail-drawer'),'No button workbench');
const styleSelect=document.querySelector('.drawer-controls select');check(styleSelect.options.length===18,'Style options missing');check([...styleSelect.options].every(option=>/[\u4e00-\u9fff]/.test(option.textContent)&&/[A-Za-z]/.test(option.textContent)&&option.value.startsWith('button-')===false),'Styles need bilingual labels and stable API values');flushSync(()=>{styleSelect.value='retro';styleSelect.dispatchEvent(new Event('change',{bubbles:true}));});check(document.querySelector('.workbench-code code').textContent.includes('variant="retro"'),'Style label leaked into code value');check(getComputedStyle(document.querySelector('.ui-detail-preview button')).borderTopWidth==='2px','Retro style not rendered');flushSync(()=>{styleSelect.value='solid';styleSelect.dispatchEvent(new Event('change',{bubbles:true}));});
click(document.querySelector('.drawer-controls input[type=checkbox]'));check(document.querySelector('.ui-detail-preview button').disabled,'Loading did not disable button');check(document.querySelector('.workbench-code code').textContent.includes('loading={true}'),'Usage did not update');
edit(document.querySelector('input[aria-label="主题色"]'),'#123456');check(document.querySelector('.ui-detail-preview button').style.getPropertyValue('--zc-accent')==='#123456','Theme did not update');check(document.querySelector('.workbench-code code').textContent.includes('#123456'),'Theme missing from code');
edit(document.querySelector('input[aria-label="圆角（px）"]'),'27');check(getComputedStyle(document.querySelector('.ui-detail-preview button')).borderRadius==='27px','Radius did not update');
click([...document.querySelectorAll('.code-tabs button')].find(e=>e.textContent==='完整源码'));check(document.querySelector('.workbench-code code').textContent.includes('export function Button'),'Real source missing');
detailGeometry('Button source');
click(document.querySelector('.drawer-close'));tab('表单');check(document.querySelectorAll('.effect-card').length===6,'Form filter failed');const toggle=document.querySelector('[role=switch]');click(toggle);check(!toggle.checked,'Switch not interactive');
const inputCard=[...document.querySelectorAll('.effect-card')].find(e=>e.querySelector('.card-meta h3').textContent==='输入框');click(inputCard.querySelector('.ui-configure'));edit(document.querySelector('.ui-detail-preview .zc-input'),'中文 custom');check(document.querySelector('.workbench-code code').textContent.includes('中文 custom'),'Input value not copied');click(document.querySelector('.drawer-close'));
tab('导航');const first=document.querySelector('.zc-tabs [role=tab]');flushSync(()=>first.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true})));check(document.querySelectorAll('.zc-tabs [role=tab]')[1].getAttribute('aria-selected')==='true','Tabs arrow key failed');check(document.activeElement===document.querySelectorAll('.zc-tabs [role=tab]')[1],'Tabs keyboard focus failed');
tab('展示');click(document.querySelector('.zc-accordion summary'));check(document.querySelector('.zc-accordion').open,'Native accordion did not expand');
for(const name of ['内容卡片','标签页']){tab(name==='标签页'?'导航':'展示');const card=[...document.querySelectorAll('.effect-card')].find(e=>e.querySelector('.card-meta h3').textContent===name);click(card.querySelector('.ui-configure'));click([...document.querySelectorAll('.code-tabs button')].find(e=>e.textContent==='完整源码'));detailGeometry(name);const preview=document.querySelector('.ui-detail-preview');check(getComputedStyle(preview).whiteSpace==='normal','Generic component inherited text no-wrap');click(document.querySelector('.drawer-close'));}
tab('反馈');click(document.querySelector('.ui-configure'));check(document.querySelector('.ui-detail-preview [role=progressbar]').getAttribute('aria-valuenow')==='68','Progress preview failed');click(document.querySelector('.drawer-close'));
const motionReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;check(getComputedStyle(document.querySelector('.zc-spinner-ring')).animationName===(motionReduced?'none':'zc-spinner-rotate'),'Spinner reduced motion failed');check(getComputedStyle(document.querySelector('.zc-skeleton-line')).animationName===(motionReduced?'none':'zc-skeleton-sweep'),'Skeleton reduced motion failed');click(document.querySelector('.hero-actions .ghost-button'));check(getComputedStyle(document.querySelector('.zc-spinner-ring')).animationPlayState==='paused','Global spinner pause failed');check(getComputedStyle(document.querySelector('.zc-skeleton-line')).animationPlayState==='paused','Global skeleton pause failed');click(document.querySelector('.hero-actions .ghost-button'));
tab('AI');check(document.querySelectorAll('.effect-card').length===6,'AI category failed');
const conversation=document.querySelector('.zc-conversation');edit(conversation.querySelector('textarea'),'你好 AI');click(conversation.querySelector('button[type=submit]'));check(conversation.querySelectorAll('.zc-conversation-message').length===2,'Local chat did not reply');check(conversation.querySelector('textarea').value==='','Chat did not clear input');
const prompt=document.querySelector('.zc-prompt-input');edit(prompt.querySelector('textarea'),'输入法内容');flushSync(()=>prompt.querySelector('textarea').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true})));check(prompt.querySelector('textarea').value==='输入法内容','IME Enter sent prematurely');click(prompt.querySelector('button[type=submit]'));check(prompt.parentElement.textContent.includes('已提交：输入法内容'),'Prompt submit callback failed');
check(getComputedStyle(document.querySelector('.zc-thinking-indicator i')).animationName===(motionReduced?'none':'zc-thinking-indicator-pulse'),'Thinking reduced motion failed');click(document.querySelector('.zc-prompt-suggestions button'));check(document.querySelector('.zc-prompt-suggestions').parentElement.textContent.includes('已选择：'),'Suggestion callback failed');
for(const card of [...document.querySelectorAll('.effect-card')]){const name=card.querySelector('.card-meta h3').textContent;click(card.querySelector('.ui-configure'));click([...document.querySelectorAll('.code-tabs button')].find(e=>e.textContent==='完整源码'));detailGeometry(name);check(document.querySelector('.workbench-code code').textContent.includes('export function'),'AI source missing');if(name==='AI 对话框'){edit(document.querySelector('.ui-detail-preview textarea'),'详情对话');click(document.querySelector('.ui-detail-preview button[type=submit]'));check(document.querySelector('.workbench-code code').textContent.includes('详情对话'),'Chat history not copied');click([...document.querySelectorAll('.workbench-actions button')].find(e=>e.textContent==='恢复默认'));check(document.querySelectorAll('.ui-detail-preview .zc-conversation-message').length===0,'Chat reset retained messages');}click(document.querySelector('.drawer-close'));}
let delivered='';const externalHost=document.createElement('div');document.body.append(externalHost);const externalRoot=createRoot(externalHost);function ExternalChat(){const[messages,setMessages]=React.useState([]);return React.createElement(Conversation,{messages,onMessagesChange:setMessages,onSend:text=>{delivered=text;setMessages(current=>[...current,{id:'external-reply',speaker:'assistant',content:'外部应用回调结果'}]);}})}flushSync(()=>externalRoot.render(React.createElement(ExternalChat)));edit(externalHost.querySelector('textarea'),'外部消息');click(externalHost.querySelector('button[type=submit]'));check(delivered==='外部消息','External chat callback failed');check(externalHost.querySelectorAll('.zc-conversation-message').length===2,'Controlled message update failed');check(externalHost.textContent.includes('外部应用回调结果')&&!externalHost.textContent.includes('这是一条本地演示回复'),'External mode generated a fake reply');flushSync(()=>externalRoot.unmount());externalHost.remove();
tab('文字');check(document.querySelectorAll('.effect-card').length===48,'Text effects missing');check(document.querySelector('[aria-label="文字效果筛选"]'),'Text subfilters missing');
for(const name of ['手绘高亮','流光渐变','霓虹灯牌','打字机','信号故障']){const card=[...document.querySelectorAll('.effect-card')].find(e=>e.querySelector('.card-meta h3').textContent===name);click(card.querySelector('.effect-preview'));const sourceTab=[...document.querySelectorAll('.code-tabs button')].find(e=>e.textContent==='完整源码');check(sourceTab,'Text source tab missing: '+name);click(sourceTab);detailGeometry(name);click(document.querySelector('.drawer-close'));}
click([...document.querySelectorAll('[aria-label="文字效果筛选"] button')].find(e=>e.textContent==='鼠标互动'));check(document.querySelectorAll('.effect-card').length===10,'Text subfilter failed');
check(document.documentElement.scrollWidth<=innerWidth,'Page overflows horizontally');
tab('按钮');const shiny=document.querySelector('.zc-button--shiny');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;check(getComputedStyle(shiny,'::before').animationName===(reduced?'none':'zc-button-shine'),'Motion preference failed');
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const settle=async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await wait(80)};
const awaitReveal=async card=>{for(let i=0;i<35;i++){const animation=card.getAnimations().find(a=>a.id.startsWith('page-reveal-'));if(animation)return animation;await wait(20)}throw Error('Scroll reveal did not trigger')};
const revealCard=document.querySelector('.effect-card');
const enterCard=async()=>{const top=revealCard.getBoundingClientRect().top+scrollY;scrollTo({top:Math.max(0,top-250),behavior:'instant'});await settle()};
await enterCard();
check(getComputedStyle(document.querySelector('.motion-aurora i')).animationName===(reduced?'none':'motion-aurora-drift'),'Aurora motion preference failed');
if(!reduced){
  const initial=await awaitReveal(revealCard);
  scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'});await settle();
  check(!revealCard.getAnimations().some(a=>a.id.startsWith('page-reveal-')),'Offscreen animation not cancelled');
  await enterCard();const returning=await awaitReveal(revealCard);
  check(returning!==initial,'Scroll back did not replay');
  check(returning.effect.getKeyframes()[0].translate.includes('-80px'),'Upward reveal direction incorrect');
  scrollTo({top:0,behavior:'instant'});await settle();await enterCard();
  const again=await awaitReveal(revealCard);check(again!==returning,'Second downward pass did not replay');
  check(!again.effect.getKeyframes()[0].translate.includes('-80px'),'Downward reveal direction incorrect');
  check(document.documentElement.scrollWidth<=innerWidth,'Active reveal creates horizontal overflow');
}else check(!revealCard.getAnimations().some(a=>a.id.startsWith('page-reveal-')),'Reduced motion still runs page reveals');
const bounds=revealCard.getBoundingClientRect();
revealCard.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerType:'mouse',clientX:bounds.left+bounds.width*.8,clientY:bounds.top+bounds.height*.2}));await settle();
const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;
check(revealCard.classList.contains('is-pointer-active')===(!reduced&&fine),'Pointer motion preference failed');
if(!reduced&&fine)check(revealCard.style.getPropertyValue('--tilt-x')!==''&&getComputedStyle(revealCard).transform!=='none','Card tilt not applied');
click(document.querySelector('.hero-actions .ghost-button'));await settle();
check(!revealCard.classList.contains('is-pointer-active'),'Pause retained pointer tilt');
check(!revealCard.getAnimations().some(a=>a.id.startsWith('page-reveal-')),'Pause retained scroll reveal');
const ribbonStyle=getComputedStyle(document.querySelector('.motion-ribbon-track'));
check(reduced?ribbonStyle.animationName==='none':ribbonStyle.animationPlayState==='paused','Pause did not stop kinetic ribbon');
click(document.querySelector('.hero-actions .ghost-button'));
document.querySelector('#result').textContent=JSON.stringify({passed:true,reduced,width:innerWidth,finePointer:fine});
} catch(error){document.querySelector('#result').textContent=JSON.stringify({passed:false,error:error.message})}})();`);
const result = await build({ configFile:false, logLevel:"error", plugins:[reactPlugin()], resolve:{alias:{"@":root,"react":path.join(root,"node_modules/react"),"react-dom":path.join(root,"node_modules/react-dom")}}, define:{"process.env.NODE_ENV":'"production"'}, build:{write:false,minify:true,lib:{entry,formats:["iife"],name:"UIFixture"}} });
const js = (Array.isArray(result) ? result : [result]).flatMap(item=>item.output).filter(item=>item.type==="chunk").map(item=>item.code).join("\n");
const css = readFileSync(path.join(root,"app/globals.css"),"utf8") + ["button","switch","progress","input","textarea","select","checkbox","slider","badge","card","alert","spinner","skeleton","accordion","tabs","conversation","chat-message","prompt-input","thinking-indicator","prompt-suggestions","reasoning-panel"].map(kind=>readFileSync(path.join(root,`components/ui/${kind}/${kind}.css`),"utf8")).join("\n");
const html = path.join(temp,"fixture.html");
writeFileSync(html,`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style><div id="app"></div><pre id="result" hidden>pending</pre><script>${js}</script>`);
for (const width of [390,720,820,1024,1440]) for (const reduced of [false,true]) {
  const screenshot = reduced ? undefined : path.join(temp, `workbench-${width}.png`);
  const motionScreenshots = !reduced && (width === 1440 || width === 390) ? { hero: path.join(temp, `motion-hero-${width}.png`), library: path.join(temp, `motion-library-${width}.png`) } : undefined;
  const data = await checkViewport({ browser, profile: path.join(temp, `profile-${width}-${reduced}`), url: pathToFileURL(html).href, width, reduced, screenshot, motionScreenshots, sourceMode: true, screenshotCategory: "AI", screenshotCode: width === 720 });
  assert.equal(data.passed,true,JSON.stringify(data));assert.equal(data.reduced,reduced);
  assert.equal(data.width,width,"Browser viewport does not match the requested test width");
  process.stdout.write(`UI browser checks passed: ${data.width}px, reduced=${reduced}\n`);
  if (screenshot) process.stdout.write(`Workbench screenshot: ${screenshot}\n`);
  if (motionScreenshots) process.stdout.write(`Motion screenshots: ${JSON.stringify(motionScreenshots)}\n`);
}
