"use client";
import { useState } from "react"; import { ShimmerText,TypewriterText,WaveText } from "@/components/text-effects";
import { getCopyEffectCode } from "@/lib/copy-effect-code";
export type LoopEffectId="typewriter"|"shimmer"|"wave"; type Mode="react"|"source"|"html"; type Props={effect:LoopEffectId;text:string;onTextChange:(v:string)=>void;fontSize:number;onFontSizeChange:(v:number)=>void;duration:number;onDurationChange:(v:number)=>void;paused:boolean};
const defaults={typewriter:{typingSpeed:90,deletingSpeed:45,holdDelay:1200,startDelay:200,cursor:"|",loop:"yes"},shimmer:{baseColor:"#777777",shineColor:"#ffffff",angle:100,width:24},wave:{amplitude:12,stagger:.06,accentColor:"#d9ff57",direction:"up"}};
const labels={typewriter:["打字机参数","输入、删除与光标"],shimmer:["扫光参数","颜色、角度与宽度"],wave:["波浪参数","振幅、节奏与方向"]} as const;
export function LoopEffectWorkbench({effect,text,onTextChange,fontSize,onFontSizeChange,duration,onDurationChange,paused}:Props){const [values,setValues]=useState<Record<string,string|number>>({...defaults[effect]});const [mode,setMode]=useState<Mode>("react");const [key,setKey]=useState(0);const [copied,setCopied]=useState(false);
  const options=effect==="typewriter"?{typingSpeed:Number(values.typingSpeed),deletingSpeed:Number(values.deletingSpeed),holdDelay:Number(values.holdDelay),startDelay:Number(values.startDelay),cursor:String(values.cursor),loop:values.loop==="yes",paused}:{...values,duration,paused};
  const outputs=getCopyEffectCode(effect,text,options,fontSize);const code=outputs[mode];
  const preview=effect==="typewriter"?<TypewriterText key={key} typingSpeed={Number(values.typingSpeed)} deletingSpeed={Number(values.deletingSpeed)} holdDelay={Number(values.holdDelay)} startDelay={Number(values.startDelay)} cursor={String(values.cursor)} loop={values.loop==="yes"} paused={paused}>{text}</TypewriterText>:effect==="shimmer"?<ShimmerText key={key} baseColor={String(values.baseColor)} shineColor={String(values.shineColor)} angle={Number(values.angle)} width={Number(values.width)} duration={duration} paused={paused}>{text}</ShimmerText>:<WaveText key={key} amplitude={Number(values.amplitude)} stagger={Number(values.stagger)} accentColor={String(values.accentColor)} direction={values.direction as "up"|"down"} duration={duration} paused={paused}>{text}</WaveText>;
  const range=(name:string,label:string,min:number,max:number,step:number,unit="")=><label><span>{label} <b>{values[name]}{unit}</b></span><input type="range" min={min} max={max} step={step} value={values[name]} onChange={e=>setValues(v=>({...v,[name]:Number(e.target.value)}))}/></label>;const color=(name:string,label:string)=><label className="color-control"><span>{label} <b>{String(values[name]).toUpperCase()}</b></span><span className="color-input-row"><input type="color" value={String(values[name])} onChange={e=>setValues(v=>({...v,[name]:e.target.value}))}/><input value={values[name]} onChange={e=>setValues(v=>({...v,[name]:e.target.value}))}/></span></label>;
  const reset=()=>{setValues({...defaults[effect]});onFontSizeChange(36);onDurationChange(1.8);setKey(v=>v+1)};const copy=async()=>{await navigator.clipboard.writeText(code);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};
  return <div className="highlight-workbench visual-workbench"><div className="workbench-stage"><div className="stage-heading"><span>实时预览</span><b>循环效果可随时重播</b></div><div className="drawer-preview highlight-preview" style={{fontSize:`${fontSize}px`}}>{preview}</div><div className="workbench-actions"><button onClick={()=>setKey(v=>v+1)}>↻ 重播</button><button onClick={reset}>恢复默认</button></div><dl className="stage-summary"><div><dt>效果</dt><dd>{labels[effect][1]}</dd></div><div><dt>字号</dt><dd>{fontSize}px</dd></div><div><dt>输出</dt><dd>{effect==="typewriter"?"2 种 React 代码":"3 种代码"}</dd></div></dl></div><div className="workbench-editor"><div className="editor-heading"><div><span>{labels[effect][0]}</span><b>{labels[effect][1]}</b></div><button onClick={reset}>重置参数</button></div><div className="drawer-controls highlight-controls"><label className="control-wide"><span>预览文字</span><input value={text} onChange={e=>onTextChange(e.target.value||" ")}/></label><label><span>字号 <b>{fontSize}px</b></span><input type="range" min="24" max="64" value={fontSize} onChange={e=>onFontSizeChange(Number(e.target.value))}/></label>{effect!=="typewriter"&&<label><span>动画时长 <b>{duration.toFixed(1)}s</b></span><input type="range" min=".2" max="8" step=".1" value={duration} onChange={e=>onDurationChange(Number(e.target.value))}/></label>}
  {effect==="typewriter"&&<><label><span>词组循环</span><select value={values.loop} onChange={e=>setValues(v=>({...v,loop:e.target.value}))}><option value="yes">开启</option><option value="no">关闭</option></select></label>{range("startDelay","开始延迟",0,2000,50,"ms")}{range("typingSpeed","输入速度",20,240,5,"ms")}{range("deletingSpeed","删除速度",10,160,5,"ms")}{range("holdDelay","停留时间",200,3000,100,"ms")}<label><span>光标字符</span><input value={values.cursor} maxLength={2} onChange={e=>setValues(v=>({...v,cursor:e.target.value}))}/></label></>}{effect==="shimmer"&&<>{color("baseColor","基础颜色")}{color("shineColor","高光颜色")}{range("angle","扫光角度",0,180,1,"°")}{range("width","高光宽度",5,60,1,"%")}</>}{effect==="wave"&&<>{color("accentColor","强调颜色")}{range("amplitude","波浪振幅",0,40,1,"px")}{range("stagger","字符间隔",0,.25,.005,"s")}<fieldset className="direction-control control-wide"><legend>波浪方向</legend><div>{[["up","向上"],["down","向下"]].map(([v,l])=><button key={v} type="button" className={values.direction===v?"active":""} onClick={()=>setValues(x=>({...x,direction:v}))}>{l}</button>)}</div></fieldset></>}</div><section className="generated-code"><div className="code-tabs">{(["react","source","html"] as Mode[]).map(v=><button key={v} disabled={v==="html"&&!outputs.htmlAvailable} title={v==="html"&&!outputs.htmlAvailable?"打字机需要 React 状态与计时逻辑":undefined} className={mode===v?"active":""} onClick={()=>setMode(v)}>{v==="react"?"React 用法":v==="source"?"完整源码":"HTML + CSS"}</button>)}</div><div className="code-box workbench-code"><div><span>{mode==="html"?"HTML + CSS":"TSX"}</span><button onClick={copy}>{copied?"已复制 ✓":"复制当前代码"}</button></div><pre><code>{code}</code></pre></div><p className="code-hint">{outputs.htmlAvailable?"完整源码包含实际 TSX、CSS 和所需辅助文件，请保留目录结构。":"打字机需要 React 状态和计时逻辑，不提供纯 HTML + CSS。完整源码包含所有依赖文件。"}</p></section></div></div>}
