import type { ButtonVariant } from "../ui/button/Button";
export const componentCategories = ["全部", "文字", "按钮", "表单", "导航", "展示", "反馈", "AI"] as const;
export type ComponentCategory = typeof componentCategories[number];
export type UIKind = "button" | "switch" | "progress" | "input" | "textarea" | "select" | "checkbox" | "slider" | "badge" | "card" | "alert" | "spinner" | "skeleton" | "accordion" | "tabs" | "chat-message" | "prompt-input" | "thinking-indicator" | "prompt-suggestions" | "reasoning-panel" | "conversation";
export type UIEntry = { id: string; name: string; en: string; category: Exclude<ComponentCategory, "全部" | "文字">; description: string; kind: UIKind; variant?: ButtonVariant };
export const uiCatalog: UIEntry[] = [
  { id: "button-solid", name: "基础按钮", en: "Button", category: "按钮", kind: "button", variant: "solid", description: "清晰的主操作，支持尺寸、禁用和加载状态。" },
  { id: "button-outline", name: "描边按钮", en: "Outline Button", category: "按钮", kind: "button", variant: "outline", description: "轻量描边，适合次级操作。" },
  { id: "button-ghost", name: "轻量按钮", en: "Ghost Button", category: "按钮", kind: "button", variant: "ghost", description: "无背景的轻量操作入口。" },
  { id: "button-gradient", name: "渐变按钮", en: "Gradient Button", category: "按钮", kind: "button", variant: "gradient", description: "渐变色面突出关键行动。" },
  { id: "button-shiny", name: "扫光按钮", en: "Shiny Button", category: "按钮", kind: "button", variant: "shiny", description: "缓慢扫光，支持暂停及减少动画偏好。" },
  { id: "button-lift", name: "立体按钮", en: "Lift Button", category: "按钮", kind: "button", variant: "lift", description: "按下时下沉，提供明确触觉式反馈。" },
  { id: "button-soft", name: "柔色按钮", en: "Soft Button", category: "按钮", kind: "button", variant: "soft", description: "低饱和色面与主题色文字，适合辅助操作。" },
  { id: "button-danger", name: "危险操作", en: "Danger Button", category: "按钮", kind: "button", variant: "danger", description: "强调删除等需要慎重处理的操作。" },
  { id: "button-pill", name: "胶囊按钮", en: "Pill Button", category: "按钮", kind: "button", variant: "pill", description: "大圆角的紧凑操作按钮。" },
  { id: "button-neon", name: "霓虹按钮", en: "Neon Button", category: "按钮", kind: "button", variant: "neon", description: "细描边配合柔和光晕，可调主题色。" },
  { id: "button-border", name: "渐变边框", en: "Border Button", category: "按钮", kind: "button", variant: "border", description: "保留深色字面，以双色边框突出入口。" },
  { id: "button-rainbow", name: "流动色带", en: "Rainbow Button", category: "按钮", kind: "button", variant: "rainbow", description: "流动渐变背景，可调速度并暂停。" },
  { id: "button-glass", name: "玻璃按钮", en: "Glass Button", category: "按钮", kind: "button", variant: "glass", description: "半透明表面配合背景模糊，可定制边框与主题色。" },
  { id: "button-striped", name: "斜纹按钮", en: "Striped Button", category: "按钮", kind: "button", variant: "striped", description: "主题色上的细斜纹，为操作增加纹理。" },
  { id: "button-dashed", name: "虚线按钮", en: "Dashed Button", category: "按钮", kind: "button", variant: "dashed", description: "虚线轮廓，适合添加或创建入口。" },
  { id: "button-minimal", name: "极简线条", en: "Minimal Button", category: "按钮", kind: "button", variant: "minimal", description: "以底部细线突出轻量操作。" },
  { id: "button-spotlight", name: "聚光按钮", en: "Spotlight Button", category: "按钮", kind: "button", variant: "spotlight", description: "径向高光在悬停和聚焦时显现，暂停时保持静态。" },
  { id: "button-retro", name: "复古按钮", en: "Retro Button", category: "按钮", kind: "button", variant: "retro", description: "粗边框与偏移硬阴影，按下时自然落位。" },
  { id: "switch", name: "开关", en: "Switch", category: "表单", kind: "switch", description: "原生 checkbox 语义与键盘操作，支持受控和非受控用法。" },
  { id: "progress", name: "进度条", en: "Progress", category: "反馈", kind: "progress", description: "显示任务进度，提供可读数值与无障碍状态。" },
  { id: "input", name: "输入框", en: "Input", category: "表单", kind: "input", description: "支持输入类型、占位提示、禁用与表单属性。" },
  { id: "textarea", name: "多行输入", en: "Textarea", category: "表单", kind: "textarea", description: "可调行数的多行编辑区域，支持原生表单行为。" },
  { id: "select", name: "选择器", en: "Native Select", category: "表单", kind: "select", description: "原生选项菜单，保留键盘操作与移动端体验。" },
  { id: "checkbox", name: "复选框", en: "Checkbox", category: "表单", kind: "checkbox", description: "用于勾选偏好和多选项目，支持受控状态。" },
  { id: "slider", name: "滑块", en: "Slider", category: "表单", kind: "slider", description: "用鼠标或方向键调整数值，可设置步长。" },
  { id: "tabs", name: "标签页", en: "Tabs", category: "导航", kind: "tabs", description: "带面板关联、方向键切换与独立实例 ID 的内容导航。" },
  { id: "badge", name: "状态徽章", en: "Badge", category: "展示", kind: "badge", description: "展示状态与分类，支持四种语义色。" },
  { id: "card", name: "内容卡片", en: "Card", category: "展示", kind: "card", description: "组合标题、说明与内容，可切换投影。" },
  { id: "accordion", name: "折叠面板", en: "Accordion", category: "展示", kind: "accordion", description: "原生 details / summary，实现可键盘展开的内容区域。" },
  { id: "alert", name: "提示信息", en: "Alert", category: "反馈", kind: "alert", description: "信息、成功、警告与错误提示；按需设置播报语义。" },
  { id: "spinner", name: "加载指示", en: "Spinner", category: "反馈", kind: "spinner", description: "可调大小和速度的加载状态，支持暂停与减少动画。" },
  { id: "skeleton", name: "骨架屏", en: "Skeleton", category: "反馈", kind: "skeleton", description: "以可调行数和高度的占位条展示加载过程。" },
  { id: "conversation", name: "AI 对话框", en: "Conversation", category: "AI", kind: "conversation", description: "可发送消息的完整对话面板，支持本地演示与外部消息接入。" },
  { id: "chat-message", name: "聊天气泡", en: "Chat Message", category: "AI", kind: "chat-message", description: "用户与助手消息、头像及作者名称，可定制文字和配色。" },
  { id: "prompt-input", name: "消息输入框", en: "Prompt Input", category: "AI", kind: "prompt-input", description: "支持发送、禁用和处理中状态，保留输入法及 Shift+Enter 换行。" },
  { id: "thinking-indicator", name: "思考状态", en: "Thinking Indicator", category: "AI", kind: "thinking-indicator", description: "可暂停的三点思考提示，支持系统减少动画偏好。" },
  { id: "prompt-suggestions", name: "建议提示词", en: "Prompt Suggestions", category: "AI", kind: "prompt-suggestions", description: "可点击的问题建议，支持自定义列表与选择回调。" },
  { id: "reasoning-panel", name: "过程摘要", en: "Reasoning Panel", category: "AI", kind: "reasoning-panel", description: "可展开的处理摘要，展示处理中与完成状态。" },
];
